### ISSUE TITLE
FiveIconDock - Rootless - the extra icon doesn't always stay in the dock

### ISSUE THREAD

**Issue by jalsco** [maxiwee69/tweaks#1]
FiveIconDock - Rootless - the extra icon doesn't always stay in the dock

Hey - thanks for some nice software ! 🙏🏻😊

I am on ver  0.0.1-5+debug of that tweak. 

Running on iOS 15.4.1 jb by Dopamine. 

I notice that sometimes - usually after extended period of phone locked - the 5th icon is not still in the dock. However the extra space for the 5th icon is still there, in the  dock. And phone is still JB-ed .  Seems no crashes or other behavior. I just move it back...   I used a different 5iconDock tweak for many years before on iOS 14 (jb by uncover)  and only had to move  the 5th icon back into the dock when re-jailbreaking.

**Comment by maxiwee69** [comment]
I didn't encounter that issue and sadly I don't have any device jailbreakable anymore so I can't really test it and try to fix it. If we get a jailbreak for 17.0 or 17.2 I can work on fixing it as long as this isn't the case I suggest you try to use Atria(I think that's on havoc or chariz repo)

**Comment by jalsco** [comment]
thanks for reply - further investigation my side has proven that FiveIconDock was not likely the problem.  

It seems working now without that symptom
